"""added image_embeddings table

Revision ID: fe40d53423a8
Revises: c571e6435bc9
Create Date: 2025-01-24 22:36:46.548413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe40d53423a8'
down_revision = 'c571e6435bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=120), nullable=False),
    sa.Column('image_name', sa.String(length=120), nullable=False),
    sa.Column('embedding', sa.PickleType(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_embeddings')
    # ### end Alembic commands ###
